### ISSUE TITLE
Set Up Wizard ****

### ISSUE THREAD

**Issue by Shoalsteed** [Shoalsteed/UX#47] opened 2021-11-23 16:36 UTC
I think that the set up wizard could use a touch up for the next release.

**Comment by Shoalsteed** [comment] 2021-11-23 16:45
CHANGE LAST SLIDE TO:


- We suggest using Firefox as your browser option to search the I2P network. If you do not have it installed, you can do that here. (link) 
- If you have not ran the bandwidth test , you can always do that later or adjust it later. 
- Ensure that when using the I2P network that being aware of your own safety still is important. Consider your identity, and use caution as you would on the clearnet when interacting with links, downloads and revealing any personal information.

**Comment by eyedeekay** [comment] 2021-11-23 16:53
It got a pretty sizable CSS touch-up this cycle, to prep for the Theme-Picker page this cycle. It's too far past tag freeze for us to push this change but we can try and get it in in 1.7.0

**Comment by Shoalsteed** [comment] 2021-11-23 16:58
what was the css change?

**Comment by eyedeekay** [comment] 2021-11-23 17:14
![Screenshot 2021-11-23 at 17-13-26 I2P Router Console - New Install Wizard](https://user-images.githubusercontent.com/8733713/143071984-b3d339cd-a008-4ba7-9c89-c93faa72aec0.png)
![Screenshot 2021-11-23 at 17-13-16 I2P Router Console - New Install Wizard](https://user-images.githubusercontent.com/8733713/143072004-9a142904-cfd5-492d-a951-67b115f9a6d1.png)
![Screenshot 2021-11-23 at 17-13-05 I2P Router Console - New Install Wizard](https://user-images.githubusercontent.com/8733713/143072010-4adfd3b7-15cc-4b95-b507-9fe2765a4443.png)
![Screenshot 2021-11-23 at 17-12-55 I2P Router Console - New Install Wizard](https://user-images.githubusercontent.com/8733713/143072021-7401850b-e0ed-446b-9531-a93034627b41.png)
![Screenshot 2021-11-23 at 17-12-43 I2P Router Console - New Install Wizard](https://user-images.githubusercontent.com/8733713/143072030-ff2906ef-3a56-4b66-928d-d59c4f43d444.png)
![Screenshot 2021-11-23 at 17-12-34 I2P Router Console - New Install Wizard](https://user-images.githubusercontent.com/8733713/143072043-11165563-88ef-4441-87a9-a51834a731fc.png)
![Screenshot 2021-11-23 at 17-12-26 I2P Router Console - New Install Wizard](https://user-images.githubusercontent.com/8733713/143072056-6ff24d5d-738e-4ff5-835c-75d62d09dd6d.png)

**Comment by eyedeekay** [comment] 2021-11-23 17:19
![Screenshot 2021-11-23 at 17-16-02 I2P Router Console - New Install Wizard](https://user-images.githubusercontent.com/8733713/143072337-0e6bab08-4cbd-436b-a149-e482d2aa901e.png)
![Screenshot 2021-11-23 at 17-15-54 I2P Router Console - New Install Wizard](https://user-images.githubusercontent.com/8733713/143072353-b9db6ba9-2f64-4776-aba0-25a38dccf5cd.png)
![Screenshot 2021-11-23 at 17-15-45 I2P Router Console - New Install Wizard](https://user-images.githubusercontent.com/8733713/143072367-e9a7a156-2588-4d47-94ca-52e4325d974e.png)
![Screenshot 2021-11-23 at 17-15-34 I2P Router Console - New Install Wizard](https://user-images.githubusercontent.com/8733713/143072375-57b3ed37-bc29-48c4-b68d-b3baf3ed9bd1.png)
![Screenshot 2021-11-23 at 17-15-23 I2P Router Console - New Install Wizard](https://user-images.githubusercontent.com/8733713/143072380-d08968ed-8517-4b18-94cd-1a903c2ffcd5.png)
![Screenshot 2021-11-23 at 17-15-14 I2P Router Console - New Install Wizard](https://user-images.githubusercontent.com/8733713/143072391-58e757b2-f739-453c-b09b-2e59e7b4e9b3.png)

**Comment by Shoalsteed** [comment] 2021-11-23 17:36
the new dark mode looks like it is creating an issue with being able to see the graphics.
What is the best way to solve that?
Do we need 2 set of graphics?

**Comment by Shoalsteed** [comment] 2021-11-23 17:37
Can this be an opportunity to swap out graphics ?

**Comment by Shoalsteed** [comment] 2021-11-23 17:48
[assets (6).zip](https://github.com/Shoalsteed/UX/files/7590102/assets.6.zip)

would these in this colour work better?
Grey tones generally are the best option for working with both light and dark themes. 
https://www.canva.com/policies/content-license-agreement/ ( some of these are pro)

**Comment by eyedeekay** [comment] 2021-11-23 19:33
We could swap them out, or recolor them. Using 2 sets is my least-favorite option but we could do that too. I don't think the ODUL thing which applies to Pro assets, is compatible with the rest of our licensing or with the licensing of many of our distribution channels. Also I just don't like it. Specifically the problem is that the assets are non-transferable. That will be inconvenient for our library users and downstreams at the very least, if not downright illegal.

**Comment by Shoalsteed** [comment] 2021-11-23 20:32
[assets (7).zip](https://github.com/Shoalsteed/UX/files/7590858/assets.7.zip)

these are free assets from canva that I modified as options to try out if we can use them with the licence.

**Comment by Shoalsteed** [comment] 2021-11-23 20:46
I would lighten the grey in the logo as well.

**Comment by Shoalsteed** [comment] 2021-11-23 20:55
I feel that in this instance there are some hard issues with visual accessibility.

The css changes for the dark them obliterate the images, I would try new assets and also the logo letters need to be lightened so that the logo is visible properly on both themes. We have a logo with white letters.

If you do not want to have 2 sets of graphic assets, then we need to modify the colours and think about using more minimal designs. 

I understand why 2 sets would be least fav, but it might need to be. Otherwise , we just make everything orange or grey I think. This dark theme option needs more time and consideration before it should be included in a release.

**Comment by Shoalsteed** [comment] 2021-11-26 19:59
What is the reasoning for introducing a dark theme in the set up wizard? 
This adds so much design complexity to a process that is not permanent. 
Also, there are big changes coming for the website, so that needs to be present in the wizard for continuity, consistency.

**Comment by eyedeekay** [comment] 2021-11-27 00:47
> What is the reasoning for introducing a dark theme in the set up wizard?

In order to offer the user a choice between a light and a dark theme for the setup wizard, and the dark theme has been there since I redid the dark theme. It's been there the entire time, all we're doing is exposing the choice.

> This adds so much design complexity to a process that is not permanent.

It is in fact permanent. It will be applied until they manually change the theme, that is the whole point.

**Comment by Shoalsteed** [comment] 2021-11-27 05:03
If this is a choice that is important, then it needs much more thought and work . The usability needs improvement. And if we are doing that, then the set up wizard as a whole can be improved.  And that is worth doing. I have wanted to do that for a while.

First off, the text is hard to read with a dark theme
The next issue is what we are focusing on. For instance: the new slide with the icons for dark and light : the big image is where I look, not at the task since that is very small. In that case it would be better to get rid of the graphic entirely and put the icons in the middle of the page and make the bigger.


Working a dark theme into this part of the process does add complexity. The set up wizard can be skipped. 

The original function of the wizard was to choose language, interact with the purpose of bandwidth and get some time for the bootstrapping process to start. In my experience a set up process usually does not handle aesthetic things. It makes sure that a few important processes happen. Personalization things come later. 

We will be limited to colours that work with both the dark and light theme unless two sets of graphics are chosen. 

**The simple option is to have a dialogue box only since that is going to be easier to manage for 2 themes. The layout and text size would need to be taken into consideration.  It leaves lots of dead space, but maybe the square logo can be used to take up more space.**

If this is going to be the first thing a new user interacts with, I would say that it needs an update and some usability focus. We have the ability to do that better now that we have design focus and support.

**Comment by Shoalsteed** [comment] 2021-11-29 17:33
There are several issue with the set up wizard that we need to fix for the next release.

-the images remain out of alignment.
-the dark theme creates a very poor experience for people who have sight issues ( and in general).
-the tasks are obscured by images. They compete for attention. 
-from a usability perspective, and for the benefit of establishing trust, the overall appearance requires improvement.

**Solutions**
-remove graphics with exception of the logo.
-use white or black logo options per theme
-centre dialogue and ensure that the text is formatted so that it is easy to read.
-for "joy" elements, include an icon from the existing icon packs we are using for language, bandwidth, etc. next to headers. This will make it easier to give a more true example of what the themes will look like and introduce the feel of the console.

**Comment by Shoalsteed** [comment] 2021-11-29 18:12
[Set Up Wizard .zip](https://github.com/Shoalsteed/UX/files/7620270/Set.Up.Wizard.zip)

**Comment by Shoalsteed** [comment] 2021-11-29 18:13
![1](https://user-images.githubusercontent.com/50714166/143920924-91f75ca0-e0c9-49d4-8844-e45973c4ac2e.png)
![2](https://user-images.githubusercontent.com/50714166/143920975-bd604fee-4800-4e38-82b9-695e223cf88e.png)
![3](https://user-images.githubusercontent.com/50714166/143920978-ba7ea02f-3bb7-4a23-92d5-ef09f0d20ad5.png)
![4](https://user-images.githubusercontent.com/50714166/143920979-5724a645-dcab-4eb0-9c32-b8a0943ba430.png)
![5](https://user-images.githubusercontent.com/50714166/143920982-883a6551-8241-41b6-91aa-3a521dc90d8e.png)

**Comment by Shoalsteed** [comment] 2021-11-29 20:16
_Copy Changes_

**Select Language** 

The Invisible Internet Project (I2P) is supported by volunteer translators on Transifex. ( link)  This helps keep I2P accessible to people all over the world.

**Comment by Shoalsteed** [comment] 2021-11-29 20:20
**Bandwidth Test** 


Bandwidth participation not only makes your speed and connection to the I2P network better, it also helps other people  using the network. Sharing as much bandwidth as possible results in better performance and privacy for everyone. 


I2P uses M-Lab, a third party service, to help you test your internet connection and find your optimal speed settings. During this time you will be connected directly to M-Lab's service with your real IP address.

To help set your bandwidth, let's check your internet connection! 
Please review the M-Lab privacy policies linked below. If you do not wish to run the M-Lab bandwidth test, you can skip it and configure your bandwidth later.

**Comment by Shoalsteed** [comment] 2021-11-29 20:22
**Bandwidth Configuration** 

You have configured I2P to share ______.
By donating your bandwidth to participating traffic, you not only help others, you improve your own anonymity and performance.
Sharing 75% or more for I2P is recommended, but you can adjust this based on your own needs.

**Comment by Shoalsteed** [comment] 2021-11-29 20:29
**Browser Set Up and Applications** 

 You will need to set up a browser to be able to access I2P network content. There are  instructions for configuring both Firefox and Chromium based browsers with I2P. You can find these instructions on the project website.

You will find I2P supported applications included in the router console. These include email, a bittorrent client, and a built in web server.  These applications work with I2P automatically and require no additional configuration.

To help make I2P addresses easier to read and remember, the I2P router also includes its built-in Address Book. The Address Book is where you keep track of all your I2P "Contacts" by giving them human-readable names. This can be used for the sites you like to visit, messaging contacts, or potentially any other service on I2P.

**Comment by Shoalsteed** [comment] 2021-11-29 20:35
**Welcome to The Invisible Internet!**



It will take time for your peers to integrate your router into the network. While that is happening you can explore I2P applications and get to know your way around the router console. You will find news about the latest release, an FAQ, and there is a troubleshooting guide available.

You may notice a message in the sidebar that I2P is rejecting tunnels. This means that your router  is connecting to the network and will soon be ready to help others with participating traffic. When the connection indicators in the sidebar turn green, you are ready to explore the Invisible Internet.

**Comment by Shoalsteed** [comment] 2022-01-06 17:37
@eyedeekay have you started any changes for this yet? We should review this and any copy changes next week.

**Closed as completed** 2022-10-20 16:31 UTC
